name: 'Lagoon CLI Action'
description: 'Run lagoon-cli commands with SSH authentication.'
author: 'amazee.io'
branding:
  icon: 'play'
  color: 'blue'

inputs:
  ssh_private_key:
    description: 'SSH private key for Lagoon authentication'
    required: true
  lagoon_graphql_endpoint:
    description: 'Lagoon GraphQL endpoint'
    required: false
    default: https://api.lagoon.amazeeio.cloud/graphql
  lagoon_ssh_hostname:
    description: 'Lagoon SSH hostname'
    required: false
    default: ssh.lagoon.amazeeio.cloud
  lagoon_port:
    description: 'Lagoon SSH port'
    required: false
    default: 32222
  lagoon_command:
    description: 'Lagoon CLI command to run'
    required: true
    default: 'whoami'
runs:
  using: 'docker'
  image: 'Dockerfile'
